# Introduction to numpy



In [2]:
import numpy as np

## Data Types & Attributes

In [3]:
# Numpys main data type is ndarray
# Single Dimension Array.
a1= np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

In [10]:
print("type",type(a1))
print("shape::",a1.shape)
print("size",a1.size)
print("ndim",a1.ndim)

type <class 'numpy.ndarray'>
shape:: (3,)
size 3
ndim 1


In [18]:
a2= np.array([[1,2,3.3],[4,5,6.5]])
print("type",type(a1))
print("shape::",a2.shape)
print("size",a2.size)
print("ndim",a2.ndim)
a2


type <class 'numpy.ndarray'>
shape:: (2, 3)
size 6
ndim 2


array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [13]:
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print("shape::",a3.shape)
print("size",a3.size)
print("ndim",a3.ndim)
a3

shape:: (3, 2, 3)
size 18
ndim 3


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [16]:

a4 = np.array([[[1, 2, 3, 0],
                [4, 5, 6, 0],
                [7, 8, 9, 0],
                [1, 1, 1, 1]],
                [[10, 11, 12, 0], 
                [13, 14, 15, 0],
                [16, 17, 18, 0],
                [1, 1, 1, 1]],
                
                [[19, 20, 21,0],
                [22, 23, 24,0],
                [25, 26, 27,0],
                [1, 1, 1,1]],
                
                [[28, 29, 30,0],
                [31, 32, 34,0],
                [35, 36, 37,0],
                [1, 1, 1,1]]
              ])

In [17]:
print("shape::",a4.shape)
print("size",a4.size)
print("ndim",a4.ndim)
a4

shape:: (4, 4, 4)
size 64
ndim 3


array([[[ 1,  2,  3,  0],
        [ 4,  5,  6,  0],
        [ 7,  8,  9,  0],
        [ 1,  1,  1,  1]],

       [[10, 11, 12,  0],
        [13, 14, 15,  0],
        [16, 17, 18,  0],
        [ 1,  1,  1,  1]],

       [[19, 20, 21,  0],
        [22, 23, 24,  0],
        [25, 26, 27,  0],
        [ 1,  1,  1,  1]],

       [[28, 29, 30,  0],
        [31, 32, 34,  0],
        [35, 36, 37,  0],
        [ 1,  1,  1,  1]]])

In [45]:
a3.shape

(3, 2, 3)

In [87]:
a4.shape

(4, 4, 4)

In [37]:
a1.shape

(3,)

In [38]:
a2.shape

(2, 3)

In [50]:
a1.ndim

1

In [51]:
a2.ndim

2

In [52]:
a3.ndim

3

In [89]:
a4.ndim

3

In [78]:
a1.dtype,a2.dtype,a3.dtype,a4.dtype

(dtype('int64'), dtype('float64'), dtype('int64'), dtype('int64'))

In [79]:
a1.size,a2.size,a3.size,a4.size

(3, 6, 18, 48)

In [80]:
type(a1),type(a2),type(a3),type(a4)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [25]:
# Create a data from numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [26]:
# Pandas cant accept 3 dimensional arrays
df = pd.DataFrame(a4)
df

ValueError: Must pass 2-d input. shape=(4, 4, 4)

# 2. Creating numpy arrays

In [27]:
sample_array= np.array([1,2,3])
sample_array
sample_array.dtype

dtype('int64')

In [28]:
ones = np.ones()

In [29]:
ones

array([1., 1.])

In [31]:
# define the shape it fills the content with ones
ones = np.ones((2,3))

In [32]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
ones = np.ones((4,2,3))

In [36]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [37]:
ones.size


24

In [38]:
ones.dtype

dtype('float64')

In [43]:
# Returns a 3*3 matrix with 2 axis 
zeros = np.zeros((2,3,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [45]:
# Returns a one dimentional array between 0 to 10 and step value of 2
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [47]:
# Returns an 3*5 array filled with values between 0 to 9
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[6, 7, 9, 0, 7],
       [8, 7, 5, 1, 2],
       [2, 0, 5, 7, 2]])

In [51]:
random_array.size
random_array.shape
random_array.dtype

dtype('int64')

In [54]:
# Returns a 3*3 array filled with values between 0.0 and 1.0
random_array_2 = np.random.random(size=(3,3))
random_array_2 

array([[0.48572421, 0.29800851, 0.17112604],
       [0.3098536 , 0.30384045, 0.7786772 ],
       [0.17922794, 0.00175991, 0.05293423]])

In [56]:
random_array_3= np.random.rand(5,3)
random_array_3

array([[0.69069061, 0.72691694, 0.0330554 ],
       [0.25162397, 0.47514313, 0.14536574],
       [0.32345709, 0.70090066, 0.49778183],
       [0.98731445, 0.43585013, 0.87608249],
       [0.35374043, 0.85025477, 0.79541816]])

In [59]:
random_array4= np.random.seed()

In [60]:
random_array4