# Introduction to numpy



In [2]:
import numpy as np

## Data Types & Attributes

In [3]:
# Numpys main data type is ndarray
# Single Dimension Array.
a1= np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

In [10]:
print("type",type(a1))
print("shape::",a1.shape)
print("size",a1.size)
print("ndim",a1.ndim)

type <class 'numpy.ndarray'>
shape:: (3,)
size 3
ndim 1


In [18]:
a2= np.array([[1,2,3.3],[4,5,6.5]])
print("type",type(a1))
print("shape::",a2.shape)
print("size",a2.size)
print("ndim",a2.ndim)
a2


type <class 'numpy.ndarray'>
shape:: (2, 3)
size 6
ndim 2


array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [13]:
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print("shape::",a3.shape)
print("size",a3.size)
print("ndim",a3.ndim)
a3

shape:: (3, 2, 3)
size 18
ndim 3


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [16]:

a4 = np.array([[[1, 2, 3, 0],
                [4, 5, 6, 0],
                [7, 8, 9, 0],
                [1, 1, 1, 1]],
                [[10, 11, 12, 0], 
                [13, 14, 15, 0],
                [16, 17, 18, 0],
                [1, 1, 1, 1]],
                
                [[19, 20, 21,0],
                [22, 23, 24,0],
                [25, 26, 27,0],
                [1, 1, 1,1]],
                
                [[28, 29, 30,0],
                [31, 32, 34,0],
                [35, 36, 37,0],
                [1, 1, 1,1]]
              ])

In [17]:
print("shape::",a4.shape)
print("size",a4.size)
print("ndim",a4.ndim)
a4

shape:: (4, 4, 4)
size 64
ndim 3


array([[[ 1,  2,  3,  0],
        [ 4,  5,  6,  0],
        [ 7,  8,  9,  0],
        [ 1,  1,  1,  1]],

       [[10, 11, 12,  0],
        [13, 14, 15,  0],
        [16, 17, 18,  0],
        [ 1,  1,  1,  1]],

       [[19, 20, 21,  0],
        [22, 23, 24,  0],
        [25, 26, 27,  0],
        [ 1,  1,  1,  1]],

       [[28, 29, 30,  0],
        [31, 32, 34,  0],
        [35, 36, 37,  0],
        [ 1,  1,  1,  1]]])

In [45]:
a3.shape

(3, 2, 3)

In [87]:
a4.shape

(4, 4, 4)

In [37]:
a1.shape

(3,)

In [38]:
a2.shape

(2, 3)

In [50]:
a1.ndim

1

In [51]:
a2.ndim

2

In [52]:
a3.ndim

3

In [89]:
a4.ndim

3

In [78]:
a1.dtype,a2.dtype,a3.dtype,a4.dtype

(dtype('int64'), dtype('float64'), dtype('int64'), dtype('int64'))

In [79]:
a1.size,a2.size,a3.size,a4.size

(3, 6, 18, 48)

In [80]:
type(a1),type(a2),type(a3),type(a4)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [25]:
# Create a data from numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [26]:
# Pandas cant accept 3 dimensional arrays
df = pd.DataFrame(a4)
df

ValueError: Must pass 2-d input. shape=(4, 4, 4)